[package]
name = "rdf-glance"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = {version="0.31.0", features = ["persistence"]}
egui = {version="0.31.0", features=["serde"]}
egui_extras = "0.31.0"
oxrdf = "0.2.4"
oxttl = "0.1.5"
rand = "0.9.0"
reqwest = {version="0.12.12", features = ["blocking"]}
rfd = "0.15.2"
serde_json = "1.0.138"
serde = { version = "1.0.138", features = ["derive"] }
indexmap = "2.7.1"
anyhow = "1.0.95"
oxrdfxml = "0.1.5"
bimap = "0.6.3"
const_format = "0.2.34"
byteorder = "1.5.0"
image = "0.25.6"

